### ISSUE TITLE
为什么查不到成绩呢

### ISSUE THREAD

**Issue by CaoCoder** [gulideshanhe/Logon-KINGOSOFT#1]
我这边通过浏览器检索 请求 能得到相关的成绩的响应。但是代码也是相同的请求，得到的响应却不同，少了成绩的group表格那一部分，很疑惑，不知道问题出现在了哪儿。

**Comment by gulideshanhe** [comment]
建议检查第58行至74行data中的键值是否与浏览器请求一致，尤其是年份及`menucode_current`

如果仍然无法解决，可在第76行添加`print(response.text)`查看请求响应内容，并在后续中附带更多信息以帮助更好的定位问题
